* Food
ЕДА
Приготовить полуфабрикаты 2t 2$ 25f +10f (за время готовки) 10m
%20 просраться -10m -1t - 20f
%80 все Ок

Купить нормальной еды  2t 4$ 35f +10f(время) 20m
5% просраться -10m -1t - 20f
95% ок

Кафе 2t 6$ 50f+10f (Время) 40m
5% просраться -10m -1t - 20f
95% ок


ОТДЫХ
Подремать -1t +10m
5% приснилась баба срака -10m
5% приснился няшный трап +10m
5% заболела голова -10m
5% хорошо прикорнул +10m
80% (нихуя не произошло)

Сидеть в интернетах -3t +40m
10% затралили -30m
10% даркоблядь опять выиграет -30m
10% Шебм с убийствами котиков :с -30m
10% Посмеялся-Обосрался +20m
10% Обдвачевался +20m
10% Затралил лалок +20m
10% серанул от скримера -10m
10% Получил 2 чая +10m
20% (нихуя не произошло)


Прибухнуть -5$ -3t +70m
10% Поймал белку -40m
90% (нихуя не произошло)

Денюшка
Искать работу -1t -20m{Уволиться -0t 0m}
Просить деньги и мамки (Доступно каждые 7 дней ) (доступно только при $<5)

список работы, с долей шанса ее нахождения
25% Форсить Рекламу 15$/3 day  4t -50m
Mail.ru и Первый канал платят за то чтобы срать их говном где только можно
25%Админ Паблика Вк 20$/5 day 5t -60m
Говнопаблик вкантактля прилично платит за то чтобы капипастить мемасы из других групп
15% Раздача флаеров ирл 8$| работа однодневка 5t - 60m
Стыдно страдать такой хуйней, но это очень выгодно, хоть и работа на один день
5% Гей шлюха 20$| работа однодневка 2t -90m
Надеюсь я не лягу под поезд после этого, должно быть очень хорошее настроение чтобы согласиться на такую работу
30% NIHUJA NE NASHOL
* Demo
Короче бля, к каждой этой кнопке есть 2 стула
1-делоть через жопу
2- купить за 200$
делоть через жопу -30m, -4t
+5% к готовности

Работа рандомно выпадает из кнопки "искать работу" может не
выпасть , потратив Настроение сделай так чтобы если это постоянная
работа, она начиналась бы на следующий день, чтобы не словить баг
с фул статами промоутер и подобная дрисня пускай будет через
несколько дней , как и ирл типа нашел, там написано ,через 3 дня,
и ты такой "мкай" и через 3 дня сдернулись статы


    То что тебе надо сделать это:
    Рандомайзер с работой, в том числе из вариантов ты можешь не найти работу.
    Далее тебе надо привести в порядок готовность звготовочки: когда графика, движок, музыка, идея закончены на 100% тогда заготовочка готова.

    Больше ничего не надо, на этом геймплей будет закончен до конца.
    Ты бы мог подумать о том как проявлять случайные события, к которым мы прийдем попозже.


    Ко всему этому надо будет сделать главное меню.
    Оно заключается в том чтобы
    - продолжить
    - начать новую игру
    При Начале новой игры предлагают выбор сложности
    »нормал
    » Абу
    Сложность Абу сделай серой, типа закрыта до судейства конкурса

    Я бы вообще хотел предложить сделать несколько экранов, типо выбираешь режим, и опираясь на каждый режим у тебя разные условия выживания


Движок*
%- обозначает процент прогресса
1.Скачать Юнити -20m - 2t +1%
2.Смотреть урок #1 Знакомство с интерфейсом -30m -3t +2%
3.Смотреть урок #2 Первые шаги -40m -3t +3%
4.Смотреть урок #3 Анимация -50m -3t +4%
5.Смотреть урок #4 Физика объектов -60m -3t +5%
6.Смотреть урок #5 Камера -70m -3t +5% //20
7.Начать Делать (нужна польностью готовая идея) -80m -4t +5% //25
8.Таскать ассеты -60m -4t +5% //30
9.Настроить анимацию -80m -5t +10% //40
10. Настроить Физику -80m -6t +10% //50
11.Делать лэвел дизайн -80m -6t +10% //60
12.Делать Главное меню -80m -5t +10% //70
13.Настройка Графики -50m -4t +10% (нужна полностью готовая графика)
14.Настройка Музыки -50m -4t +10% (нужна полностью готовая Музыка)
15.Компиляровать игру -100m -10t +10%


Идея
%- обозначает процент прогресса
1. Генерировать сюжет -1t -20m +20%*при успехе     //Игрок не перейдет на следующий пункт пока не сгенерирует что-то нормальное
	5% сгенерировать.
	>Ахуенно, теперь можно думать
	95% сгенерировать хуйню
	>Генерируется одна хуйня.

2. Расписать дизайн документ -1t -20m +20%*при успехе
	10% сгенерировать.
	сгенерировать.
	>Я сделяль
	90% сгенерировать хуйню
	>нихуя

3. Придумать главного героя -1t -20m +20%*при успехе
	10% сгенерировать.
	сгенерировать.
	>Я сделяль
	90% сгенерировать хуйню
	>нихуя

4. Придумать сюжет -1t -20m +20%*при успехе
	10% сгенерировать.
	сгенерировать.
	>Я сделяль
	90% сгенерировать хуйню
	>нихуя


5. Придумать врагов -1t -20m +20%*при успехе
	10% сгенерировать.
	сгенерировать.
	>Я кончил
	90% сгенерировать хуйню
	>нихуя

Движок
%- обозначает процент прогресса
1.Скачать Юнити -20m - 2t +1%
2.Смотреть урок #1 Знакомство с интерфейсом -30m -3t +2%
3.Смотреть урок #2 Первые шаги -40m -3t +3%
4.Смотреть урок #3 Анимация -50m -3t +4%
5.Смотреть урок #4 Физика объектов -60m -3t +5%
6.Смотреть урок #5 Камера -70m -3t +5%
7.Начать Делать (нужна польностью готовая идея) -80m -4t +5%
8.Таскать ассеты -60m -4t +5%
9.Настроить анимацию -80m -5t +10%
10. Настроить Физику -80m -6t +10%
11.Делать лэвел дизайн -80m -6t +10%
12.Делать Главное меню -80m -5t +10%
13.Настройка Графики -50m -4t +10% (нужна полностью готовая графика)
14.Настройка Музыки -50m -4t +10%  (нужна полностью готовая Музыка)
15.Компиляровать игру  -100m -10t +10%

Графика
%- обозначает процент прогресса
1.Скачать фотошоп -20m -2t 2%
2.Учиться рисованию: Форма -60m -5t  2%
3.Учиться рисованию: Перспектива -60m -5t 2%
4.Учиться рисованию: Светотень -60m -5t 2%
5.Учиться рисованию: Цвет -60m -5t 2%
	>Отлично, теперь можно пробовать себя в Pixel Art!
6.Рисовать главного героя (нужно придумать главного героя)  -100m -10t 30%
7.Рисовать окружение (нужно придумать сюжет)  -100m -10t +30%
8.Рисовать врагов (нужно придумать врагов)  -100m -10t +30%


Музыка
%- обозначает процент прогресса
1.Искать софт -1t -20m +1%*при успехе     //Игрок не перейдет на следующий пункт пока не найдет софт
	5% найти
	>Ня, теперь можно лабать
	95% не найти
	>Одна хуйня

2.Пытаться делать  -1t -20m +99%*при успехе  (нужен сюжет)
	5% найти
	>Как все ахуенно
	95% не найти
	>Как все хуево


1 скрин. Нажимаешь на работу, оттуда вываливается меню
2. скрин, после нажатия СНИМАЕЮТСЯ СТАТЫ и крутится прогрес бар и в статусе написано: поиск работы
(работа может найтись, а может нет)
3 скрин. Найдена работа! Статус: поиск работы остается пока алерт не закрыт.
В появившимся алерте написаны условия работы и описание, посе чего спрашивается, хочет ли игрок заниматься такой дрисней или нет.
4. После принятия статус Работы меняется на Раздачу листовок , гдле пишется сколько дней осталось до выхода.

5. Проходит 2 дня, на 3 дней начинается работа, статус работы становится активным, что объясняется тем что пишут зп.
Статус меняется на "на работе" 5 секунд идет прогрес бар
После конца Прогрес бара приходит Алерт о заработке "получено 8$"; Статус меняется на безработный
